version: '2'
services:
  data-updater:
    build:
      context: .
      args:
        http_proxy: 'http://192.168.31.223:1087'
    environment:
      NODE_ENV: dev
    ports:
      - "8000:8080"
    #entrypoint:
    #  - ./entrypoint.sh
